[tool.poetry]
name = "sim"
version = "0.1.0"
description = ""
authors = ["dhzdhd"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
panda3d = "1.10.14"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
